### PR TITLE
Fixed that the player inventory does not contain all items and a NPE when clicking in the inventory.

### LINKED ISSUE #108: Inventory#getContents does not contain the offhand item
**Description**
Inventory#getContents does not contain the offhand item

### PR DESCRIPTION
**Pull request by R0bbyYT**
Closes #108 and #19

### CODE REVIEW

File: mcapi/src/main/java/net/flintmc/mcapi/items/inventory/player/PlayerInventory.java [hunk 1]
```diff
@@ -104,4 +114,34 @@
...
+
+  /**
+   * Retrieves all armor parts from the armor inventory.
+   *
+   * @return An array of all armor parts from the armor inventory.
+   */
+  ItemStack[] getArmorContents();
+
+  /**
+   * Retrieves the item of the off hand.
```
Comment (Janrupf) [inline mcapi/src/main/java/net/flintmc/mcapi/items/inventory/player/PlayerInventory.java]: Maybe specify what happens if there is no off-hand due to the current minecraft version

**Review by Janrupf — CHANGES_REQUESTED** [review]

**Review by Janrupf — APPROVED** [review]
