### PR TITLE
Fix obfuscation errors

### LINKED ISSUE #124: Fix errors in obfuscated environment
Flint does not launch in obfuscated environment

### PR DESCRIPTION
**Pull request by jan-br**

### CODE REVIEW

**Review by derklaro — DISMISSED** [review]

File: transform/javassist/src/internal/java/net/flintmc/transform/javassist/internal/DefaultClassTransformService.java [hunk 1]
```diff
@@ -101,6 +106,18 @@ private void sortFactories() {
...
 
+  @Override
+  public void notifyTransform(LateInjectedTransformer transformer, String className,
+      byte[] classData) {
+    try {
+      ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(classData);
+      this.pool.makeClass(byteArrayInputStream, false);
+      byteArrayInputStream.close();
+    } catch (Exception ex) {
+      ex.printStackTrace();
```
Comment (Janrupf) [inline transform/javassist/src/internal/java/net/flintmc/transform/javassist/internal/DefaultClassTransformService.java]: Use a logger

File: transform/launcher-plugin/src/main/java/net/flintmc/transform/launchplugin/LateInjectedTransformer.java [hunk 2]
```diff
@@ -31,5 +31,11 @@
    * @return A derivative of class data.
    * @throws ClassTransformException If the class transformation failed.
    */
-  byte[] transform(String className, byte[] classData) throws ClassTransformException;
+  default byte[] transform(String className, byte[] classData) throws ClassTransformException {
+    return classData;
+  }
+
+  default void notifyTransform(LateInjectedTransformer transformer, String className,
```
Comment (Janrupf) [inline transform/launcher-plugin/src/main/java/net/flintmc/transform/launchplugin/LateInjectedTransformer.java:46]: Missing javadocs

**Review by Janrupf — CHANGES_REQUESTED** [review]

**Review by Janrupf — APPROVED** [review]
